### ISSUE TITLE
Impossible to compile the sheet.

### ISSUE THREAD

**Issue by Kazadri** [joesinghaus/Blades-template#5]
Hi;
I just clone your project and was following the readme but I was not able to compile the sheet. I got the following error :
```shell script
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'Source/Blades.pug'
```

Thankfully I just needed to remove the 'Blades.pug' to 'blades.pug' in the build.js to work again.

**Comment by joesinghaus** [comment]
Thanks, don't know how that happened. I merged your PR.
